import type { Metadata } from 'next';
import {Poppins } from 'next/font/google';
import './globals.css';
import { ThemeSwitcher } from '@/components/ui/theme-switcher';
import { ThemeProvider } from '@/providers/theme-provider';
import { NotificationProvider } from '@/components/Notification';
import LayoutWrapper from '@/components/LayoutWrapper'; // ✅ import it here

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  subsets: ['latin'],
  weight: '100'
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} antialiased`}>
        <NotificationProvider>
          <ThemeProvider attribute="class" disableTransitionOnChange>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
            <ThemeSwitcher />
          </ThemeProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
