import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeSwitcher } from "@/components/ui/theme-switcher";
import { ThemeProvider } from "@/providers/theme-provider";
// import { SessionProvider } from "next-auth/react";
import { NotificationProvider } from "@/components/Notification";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <NotificationProvider>
         <ThemeProvider attribute="class" disableTransitionOnChange>
         <Navbar/>
          {children}
          <ThemeSwitcher />
        </ThemeProvider>
        </NotificationProvider>
       
      </body>
      
    </html>
  );
}
